import type { Item } from "./types"

export const mockItems: Item[] = [
  {
    id: "1",
    name: "Premium Camera Kit",
    description:
      "Professional DSLR camera with lenses and accessories. Perfect for events, photoshoots, and videography.",
    category: "Electronics",
    price: 150,
    imageUrl: "/professional-camera-kit.jpg",
    available: true,
    availableDates: ["2026-01-15", "2026-01-16", "2026-01-20", "2026-01-21"],
  },
  {
    id: "2",
    name: "Luxury Tent Setup",
    description: "8-person camping tent with sleeping bags and camping gear. Ideal for outdoor adventures.",
    category: "Outdoor",
    price: 80,
    imageUrl: "/luxury-camping-tent-setup.jpg",
    available: true,
    availableDates: ["2026-01-18", "2026-01-19", "2026-01-25"],
  },
  {
    id: "3",
    name: "DJ Sound System",
    description: "Complete DJ setup with speakers, mixer, and lighting. Perfect for parties and events.",
    category: "Electronics",
    price: 300,
    imageUrl: "/professional-dj-sound-system.jpg",
    available: true,
    availableDates: ["2026-01-22", "2026-01-23"],
  },
  {
    id: "4",
    name: "Mountain Bike",
    description: "High-performance mountain bike for trails and adventures. Includes helmet and safety gear.",
    category: "Sports",
    price: 60,
    imageUrl: "/mountain-bike-adventure.jpg",
    available: true,
    availableDates: ["2026-01-15", "2026-01-17", "2026-01-24"],
  },
  {
    id: "5",
    name: "Party Decoration Set",
    description: "Complete decoration package for birthdays and celebrations. Includes balloons, banners, and more.",
    category: "Party",
    price: 40,
    imageUrl: "/festive-birthday-decorations.png",
    available: false,
    availableDates: [],
  },
  {
    id: "6",
    name: "Gaming Console Bundle",
    description: "Latest gaming console with controllers and popular games. Entertainment for all ages.",
    category: "Electronics",
    price: 100,
    imageUrl: "/gaming-console-bundle.png",
    available: true,
    availableDates: ["2026-01-16", "2026-01-17", "2026-01-23", "2026-01-24"],
  },
  {
    id: "7",
    name: "Projector & Screen",
    description: "HD projector with portable screen. Perfect for movie nights and presentations.",
    category: "Electronics",
    price: 120,
    imageUrl: "/portable-projector-screen.jpg",
    available: true,
    availableDates: ["2026-01-19", "2026-01-20", "2026-01-26"],
  },
  {
    id: "8",
    name: "Kayak Set",
    description: "Two-person kayak with paddles and life jackets. Great for water adventures.",
    category: "Outdoor",
    price: 90,
    imageUrl: "/two-person-kayak-adventure.jpg",
    available: true,
    availableDates: ["2026-01-21", "2026-01-22", "2026-01-27"],
  },
]
